FROM public.ecr.aws/lambda/python:3.11

RUN yum install -y postgresql-devel gcc python3-devel

COPY app/worker/handler.py ${LAMBDA_TASK_ROOT}/app/worker/handler.py

COPY requirements.txt .
COPY cookies.txt .

RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["app/worker/handler.lambda_handler"]