service: sqs-worker
plugins:
    - serverless-localstack

provider:
    name: aws
    runtime: nodejs18.x
    region: us-east-1
    environment:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/my-local-db

functions:
    processQueue:
        handler: app/worker/handler.main
        events:
            - sqs:
                  arn:
                      Fn::GetAtt:
                          - JobsQueue
                          - Arn
custom:
    esbuild:
        bundle: true
        minify: false
        target: node18
        sourcemap: true
        keepNames: true
        external: []
        tsconfig: './tsconfig.json'
    localstack:
        stages:
            - local
        host: http://localhost
        edgePort: 4566
        autostart: false
        lambda:
            mountCode: true

resources:
    Resources:
        JobsQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: JobsQueue