org: matheuspimentel
service: sqs-worker

provider:
    name: aws
    region: us-east-1
    timeout: 60
    ecr:
        images:
            sqs-worker-image:
                path: .
                file: Dockerfile.lambda

    environment:
        DATABASE_URL: ${env:DATABASE_URL}

functions:
    processQueuePython:
        image:
            name: sqs-worker-image
        events:
            - sqs:
                  arn:
                      Fn::GetAtt:
                          - JobsQueue
                          - Arn

resources:
    Resources:
        JobsQueue:
            Type: AWS::SQS::Queue
            Properties:
                QueueName: JobsQueue
